background #191724
foreground #E0DEF4

cursor #E0DEF4
selection_background #403D52
selection_foreground #E0DEF4

Black

color0 #26233A
color8 #6E6A86

Red

color1 #EB6F92
color9 #EB6F92

Green

color2 #9CCFD8
color10 #9CCFD8

Yellow

color3 #F6C177
color11 #F6C177

Blue

color4 #9CCFD8
color12 #9CCFD8

Purple

color5 #C4A7E7
color13 #C4A7E7

Rose

color6 #EBBCBA
color14 #EBBCBA

White

color7 #E0DEF4
color15 #908CAA
